## ARRAY CREATION

In [2]:
import numpy as np

In [3]:
arr1 = np.array([1,2,3,4,5])
arr1
arr1.size
arr1.ndim
arr1.shape

(5,)

In [4]:
arr2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2.shape
arr2.size
arr2.ndim

2

In [ ]:
zeros = np.zeros((4,2)) #4 rows and 2 columns
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [5]:
ones = np.ones((5,6))
ones

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [7]:
range_arr = np.arange(2, 20, 2)
range_arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
random_array = np.random.randint(1, 10 , (1,5))
random_array

array([[8, 4, 5, 9, 7]])

In [24]:
full_array = np.full((3,3), 4)
full_array

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

## INDEXING

In [31]:
random_float_array = np.random.uniform(1,10, (5,6))
random_float_array

array([[9.48444071, 5.99610584, 6.60239851, 9.03949499, 5.45970795,
        8.62655086],
       [7.98577933, 7.04416355, 5.86727937, 5.77130092, 4.81889583,
        1.52069254],
       [4.65818724, 9.25710015, 2.10064044, 1.10814937, 2.03307783,
        6.81267612],
       [1.83385616, 2.59078791, 6.48409038, 6.32140186, 1.37602454,
        3.51494955],
       [5.52631903, 9.59656182, 6.69079282, 2.73457173, 4.46072341,
        4.99836025]])

In [33]:
random_array1 = np.random.randint(1,100, (5,6))
random_array1

array([[76, 39,  4,  2, 80, 79],
       [56, 75, 64, 70, 53, 77],
       [63, 32, 43, 99, 43, 59],
       [89, 29, 32, 63, 69, 82],
       [10, 67, 81, 78, 39, 15]])

rule to remember indexing:
x to smaller than y

In [40]:
random_array1[1:4,2:]

array([[64, 70, 53, 77],
       [43, 99, 43, 59],
       [32, 63, 69, 82]])

fancy indexing:

In [42]:
rows = [1,4] # selecting rows 1 and 4
random_array1[rows, :]

array([[56, 75, 64, 70, 53, 77],
       [10, 67, 81, 78, 39, 15]])

## reshaping, concatination and splitting

In [54]:
arr3 = np.arange(1,13)
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [70]:
reshaped = arr3.reshape(3,4) # x to less than y
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [74]:
transposed = reshaped.T
transposed

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

Splitting

In [82]:
arr4 = np.arange(1,17)
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [84]:
split_arr = np.split(arr4, 4)
split_arr

[array([1, 2, 3, 4]),
 array([5, 6, 7, 8]),
 array([ 9, 10, 11, 12]),
 array([13, 14, 15, 16])]

broadcasting

In [87]:
# Broadcasting
arr2 = np.array([[1, 2], [3, 4]])
print(arr2 + np.array([1, 2]))

[[2 4]
 [4 6]]
